import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;

public class ServerFrame extends JFrame implements Runnable {
    // Variables declaration - do not modify
    private JButton btnSave;
    private JButton btnSend;
    private JLabel txtIPAddressReceiver;
    private JTextField edtInputMessage;
    private JTextField edtPort;
    private JTextField edtSenderName;
    private JLabel labelIPAddressReceiver;
    private JLabel labelSenderName;
    private JLabel labelPort;
    private JScrollPane jScrollPane1;
    private JList<String> listMessage;
    private JPanel panelChat;
    private JPanel panelConfig;
    // End of variables declaration
    private List<String> messages;
    DatagramSocket serverSocket;
    DatagramPacket receivePacket;
    InetAddress inetAddress;

    String requestByClient;
    String response = "";
    private Thread thread;

    byte[] receiveData;
    byte[] sendData;
    InetAddress IPAddress;
    int port;

    private DefaultListModel<String> listModel;
    private boolean isRunning;

    public ServerFrame() {
        setTitle("Mini Chat (Server)");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelConfig = new JPanel();
        labelIPAddressReceiver = new JLabel();
        txtIPAddressReceiver = new JLabel();
        labelSenderName = new JLabel();
        edtSenderName = new JTextField();
        labelPort = new JLabel();
        edtPort = new JTextField();
        btnSave = new JButton();
        panelChat = new JPanel();
        jScrollPane1 = new JScrollPane();
        listMessage = new JList<>();
        edtInputMessage = new JTextField();
        btnSend = new JButton();

        messages = new ArrayList<>();


        try {
            inetAddress = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }

        txtIPAddressReceiver.setText(String.valueOf(inetAddress.getHostAddress()));

        edtSenderName.setText(inetAddress.getHostName());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        panelConfig.setBorder(BorderFactory.createTitledBorder(null, "Cấu hình"));

        labelIPAddressReceiver.setText("IP Máy chủ:");


        labelSenderName.setText("Tên người gửi:");


        labelPort.setText("Cổng:");

        edtPort.addActionListener(evt -> edtPortActionPerformed(evt));

        btnSave.setText("Run Server");
        btnSave.addActionListener(evt -> {
            try {
                btnSaveActionPerformed(evt);
            } catch (IOException e) {
                e.printStackTrace();
            }
        });

        btnSend.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    btnSendActionPerformed(e);
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                }
            }
        });

        GroupLayout panelConfigLayout = new GroupLayout(panelConfig);
        panelConfig.setLayout(panelConfigLayout);
        panelConfigLayout.setHorizontalGroup(
                panelConfigLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panelConfigLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelIPAddressReceiver)
                                        .addComponent(labelSenderName))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtIPAddressReceiver, GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(edtSenderName))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelPort)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtPort, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        panelConfigLayout.setVerticalGroup(
                panelConfigLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panelConfigLayout.createSequentialGroup()
                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(panelConfigLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelIPAddressReceiver)
                                                        .addComponent(txtIPAddressReceiver, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(edtSenderName, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelSenderName)))
                                        .addGroup(panelConfigLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(panelConfigLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(labelPort)
                                                        .addComponent(edtPort, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelChat.setBorder(BorderFactory.createTitledBorder(null, "Tin nhắn"));

        listModel = new DefaultListModel<String>() {
            @Override
            public int getSize() {
                return messages.size();
            }

            @Override
            public String getElementAt(int index) {
                return messages.get(index);
            }
        };

        listMessage.setModel(listModel);
        jScrollPane1.setViewportView(listMessage);

        btnSend.setText("Gửi");

        GroupLayout panelChatLayout = new GroupLayout(panelChat);
        panelChat.setLayout(panelChatLayout);
        panelChatLayout.setHorizontalGroup(
                panelChatLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panelChatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1)
                                .addContainerGap())
                        .addGroup(panelChatLayout.createSequentialGroup()
                                .addComponent(edtInputMessage, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend, GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
        );
        panelChatLayout.setVerticalGroup(
                panelChatLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(panelChatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelChatLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(edtInputMessage, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSend, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(panelConfig, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(panelChat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelConfig, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelChat, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void edtPortActionPerformed(ActionEvent event) {
        // TODO add your handling code here:
    }

    private void btnSaveActionPerformed(ActionEvent event) throws IOException {
        if (!edtPort.getText().isEmpty()) {
            createServer();
            startThread();
        } else {
            JOptionPane.showMessageDialog(null, "Port không được để trống");
        }
    }

    private void btnSendActionPerformed(ActionEvent event) throws IOException {
        if (isRunning) {
            if (!edtPort.getText().isEmpty()) {
                sendData();
                edtInputMessage.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Port không được để trống");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Server chưa được khởi chạy");
        }
    }

    private void createServer() throws IOException {
        if (!edtPort.getText().isEmpty()) {
            int port = Integer.parseInt(edtPort.getText().trim());
            serverSocket = new DatagramSocket(port);
        } else {
            JOptionPane.showMessageDialog(null, "Port không được để trống");
        }
    }

    private void startThread() {
        thread = new Thread(this);
        thread.start();
        JOptionPane.showMessageDialog(null, "Đã khởi chạy Server...");
    }

    private void sendData() throws IOException {
        response = edtSenderName.getText() + ": " + edtInputMessage.getText();
        messages.add(response);
        listModel.addElement(response);

        sendData = response.getBytes();
        DatagramPacket sendPacket = new DatagramPacket(sendData, sendData.length, IPAddress, port);

        if (IPAddress == null) {
            JOptionPane.showMessageDialog(null, "Không có Client nào được kết nối!");
        } else {
            serverSocket.send(sendPacket);
        }
    }

    private void observe() {
        receiveData = new byte[1024];
        try {
            receivePacket = new DatagramPacket(receiveData, receiveData.length);
            serverSocket.receive(receivePacket);
            IPAddress = receivePacket.getAddress();
            port = receivePacket.getPort();
        } catch (IOException e) {
            e.printStackTrace();
        }

        requestByClient = new String(receivePacket.getData()).trim();
        System.out.println("RECEIVER: " + requestByClient);
        messages.add(requestByClient);
        listModel.addElement(requestByClient);
    }

    @Override
    public void run() {
        while (!isRunning) {
            observe();
        }
    }
}
